 # 1)Write a Program to find the area of triangle

*  Area  traingle formula is 0.5 * base* height

In [1]:
b = int(input("Enter the base of the triangle"))
h = int(input("Enter the height of the triangle"))
area = 0.5*b*h
print(f"Area of triangle is :{area}")

Enter the base of the triangle 4
Enter the height of the triangle 5


Area of triangle is :10.0


# 2) Write a program to swap two variable

In [2]:
a=5
b=10
a,b = b,a
print("After swaping the Variables")
print(f"a is:{a}")
print("b is:",b)

After swaping the Variables
a is:10
b is: 5


# Alternative solution

*with using the temp

In [5]:
a= 10
b= 20
temp = a
a = b
b = temp
print("After swaping with the temp ")
print("a is :",a)
print("b is:",b)


After swaping with the temp 
a is : 20
b is: 10


# 3) Write a Program to convert kilometers to miles

* one is equal to the 0.621371

In [6]:
kilometers = float(input("Enter distance in kilometers: "))
conversion_factor = 0.621371
miles = kilometers * conversion_factor
print(f"{kilometers} kilometers is equal to {miles} miles")


Enter distance in kilometers:  100


100.0 kilometers is equal to 62.137100000000004 miles


# 4) write a program to swap variables without temp variable 

In [7]:
a=5
b=10
a,b = b,a
print("After swaping the Variables")
print(f"a is:{a}")
print("b is:",b)

After swaping the Variables
a is:10
b is: 5


# 5)write a program to check the year is leap year or not

* If the year is divisible by 400, it is a leap year.
* If the year is divisible by 100 but not by 400, it is not a leap year.
* If the year is divisible by 4 but not by 100, it is a leap year.
* Otherwise, it is not a leap year.

In [4]:
year = int(input("Enter the your year"))
if (year % 400 == 0) and (year % 100 == 0):
 print("{0} is a leap year".format(year))
elif (year % 4 ==0) and (year % 100 != 0):
 print("{0} is a leap year".format(year))
else:
    print("it is not a leap year:",year)

Enter the your year 2020


2020 is a leap year


# Alternative solution

In [18]:
year = int(input("Enter your year to check leap year or not"))
if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):     # important
    
    print("leap year:",year)
        
else:
    print("not a leap year:",year)



Enter your year to check leap year or not 2016


leap year: 2016


# Alternative solution


In [19]:
year  = int(input("Enter your year to check leap year or not"))
if year%400 == 0:
    print("leap year :",year)
elif (year%100 ==0) and (year%400 !=0):
    print("leap year :",year)
elif (year%4 ==0) and (year%100 !=0):
    print("leap year :",year)
else:
    print("is not a leap year :",year)
    

Enter your year to check leap year or not 2024


leap year : 2024


# 6)Write a program to check Prime number or not

* A prime number is greater than 1.
* It should not be divisible by any number other than 1 and itself

In [32]:
n = int(input("Enter the number to check if it is a prime number: "))

if n <= 1:
    print("It is NOT a prime number:", n)
else:
    for i in range(2, n):
        if n % i == 0:
            print("NOT a prime number:", n)
            break  # Stop checking further because  it's not a prime number
    else:
        print("It IS a prime number:", n)

            
    

Enter the number to check if it is a prime number:  3


It IS a prime number: 3


# Alternative solution¶

In [41]:
def primenumber(n):
    if n < 2:
        print("It is NOT a prime number:", n)
        return  # Exit the function early

    for i in range(2, n):
        if n % i == 0:
            print("It is NOT a prime number:", n)
            break
    else:
        print("It IS a prime number:", n)
    
# Get user input
num = int(input("Enter the number to check if it is a prime number: "))
primenumber(num)  # Call the function


Enter the number to check if it is a prime number:  13


It IS a prime number: 13


# 7) Write a program to check factorial of a number

* The factorial of a number nis the product of all positive integers from 1 to n.
* n! = n*n-1 *n-2 * n
* 5!  = 1* 2 *3 *4 *5

In [47]:
n = int(input("Enter any number for the factorial: "))

f = 1 

for i in range(1, n + 1):
    f *= i 

print("Factorial of", n, "is", f) 

    

Enter any number for the factorial:  5


Factorial of 5 is 120


# Alternative way

In [49]:
n = int(input("Enter any number for the factorial: "))

f = 1
i = 1

while i <= n:
    f *= i
    i += 1

print("Factorial of", n, "is", f)


Enter any number for the factorial:  5


Factorial of 5 is 120


# Alternative way

In [48]:
import math

n = int(input("Enter any number for the factorial: "))
print("Factorial of", n, "is", math.factorial(n))


Enter any number for the factorial:  5


Factorial of 5 is 120


# 8)Write a program to display the multiplication of the table

In [5]:
n = int(input("Enter the number of multiples needed"))
t = int(input("enter the table number needed"))
for i in range(1,n+1):
    print(f"{t} * {i} ={t*i}")
    




Enter the number of multiples needed 10
enter the table number needed 2


2 * 1 =2
2 * 2 =4
2 * 3 =6
2 * 4 =8
2 * 5 =10
2 * 6 =12
2 * 7 =14
2 * 8 =16
2 * 9 =18
2 * 10 =20


# Alternative way

In [8]:
t = int(input("Enter a number to display its multiplication table: "))
n = int(input("Enter the range up to which you want the table: "))

def multipletable(n,t):
    for i in range(1,n+1):
        print(f"{t}*{i}={t*i}")


Enter a number to display its multiplication table:  2
Enter the range up to which you want the table:  2


In [7]:
# calling the multiple table
multipletable(10,2)

2*1=2
2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18
2*10=20


# 9)Write a program to print the fibonnaci series

* F(n)=F(n−1)+F(n−2)
* The series starts with 0 and 1 indexes is equal to the 2 index number 

In [13]:
n = int(input("Enter the number of Fibonacci series terms needed: "))

if n <= 0:
    print("No Fibonacci series are available")
else:
    # Initialize the first two terms
    fib_series = [0, 1]
    
    # Generate the series up to `n` terms
    for i in range(2, n):
        next_term = fib_series[-1] + fib_series[-2]
        fib_series.append(next_term)
    
    # Print the series
    print(f"Fibonacci series with {n} terms: {fib_series[:n]}")

            

Enter the number of Fibonacci series terms needed:  5


Fibonacci series with 5 terms: [0, 1, 1, 2, 3]


In [2]:
n = int(input("Enter the number of Fibonacci series terms needed: "))
list = [0,1]

for i in range(n+1):
    p=list[i]+list[i+1]
    list.append(p)
print(list)    
    
    

Enter the number of Fibonacci series terms needed:  8


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


# Alternative way

In [31]:
def fibonacci_series(n):
    a, b = 0, 1
    for _ in range(n):
        print(a, end=" ")
        a, b = b, a + b

# Input from the user
n = int(input("Enter the number of Fibonacci series terms needed: "))
fibonacci_series(n)


Enter the number of Fibonacci series terms needed:  5


0 1 1 2 3 

In [12]:
def fibonacci_series(n):
    a, b = 0, 1
    for i in range(n):
        if i == 0:
            print(a,end = " ")  # Print the first term
        elif i == 1:
            print(b,end = " ")  # Print the second term
        else:
            a, b = b, a + b  # Calculate the next term
            print(b,end = " ")  # Print the next term

# Input from the user
n = int(input("Enter the number of Fibonacci series terms needed: "))
fibonacci_series(n)


Enter the number of Fibonacci series terms needed:  8


0 1 1 2 3 5 8 13 

# Using the recursion funcation

In [1]:
def fibonacci(n):
    if n <= 0:
        return "Input should be a positive integer"
    elif n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

# Print Fibonacci series up to n terms
n_terms = 10  # Change this value to generate more terms
print([fibonacci(i) for i in range(1, n_terms + 1)])

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


# 10) Write a program to check the armstrong number

* An Armstrong number (also known as a narcissistic number or pluperfect digital invariant) is a number that is equal to the sum of its own digits each raised to the power of the number of digits.

* For example:

* 153 is an Armstrong number because:
* 1³ + 5³ + 3³ = 153

In [44]:

def is_armstrong_number(num):
    digits = str(num)  # numbers to string
    power = len(digits)  # Number of digits
    sum_of_powers = sum(int(digit) ** power for digit in digits)
    
    # Check if the number is equal to the sum of its digits raised to the power
    return num == sum_of_powers

# Input from the user
number = int(input("Enter a number to check if it is an Armstrong number: "))

# Check and display the result
if is_armstrong_number(number):
    print(f"{number} is an Armstrong number.")
else:
    print(f"{number} is not an Armstrong number.")


Enter a number to check if it is an Armstrong number:  153


153 is an Armstrong number.


In [46]:
n = 153

is_armstrong_number(n)

True

In [15]:
def is_armstrong_number(number):
    # Make a copy of the original number
    original_number = number                                # Simple Logical code
    sum_of_powers = 0
    
    # Loop to extract digits and calculate the sum of powers
    while number > 0:
        digit = number % 10  # Get the last digit
        sum_of_powers += digit ** len(str(original_number))  # Add the digit raised to the power of the number of digits
        number //= 10  # Remove the last digit
    
    # Check if the sum is equal to the original number
    return sum_of_powers == original_number

# Test the function with a number
num = int(input("Enter a number: "))
if is_armstrong_number(num):
    print(f"{num} is an Armstrong number.")
else:
    print(f"{num} is not an Armstrong number.")


Enter a number:  370


370 is an Armstrong number.


# 11) Write a program to find the sum of the natural numbers

In [48]:
n = int(input("Enter the needed numbers sum"))
sum = 0
for i in range(n+1):
    sum += i
print(sum)
    

Enter the needed numbers sum 2


3


# 12) Write a program to find the LCM 

* The Least Common Multiple (LCM) of two numbers is the smallest positive number that is divisible by both numbers. For example:

The LCM of 4 and 6 is 12, because 12 is the smallest number that both 4 and 6 divide evenly.


In [50]:
# Python Program to find the L.C.M. of two input number
def compute_lcm(x, y):
    if x > y:  # Choose the greater number
        greater = x
    else:
        greater = y

    while True:
        if (greater % x == 0) and (greater % y == 0):
            lcm = greater
            break
        greater += 1
    return lcm

# Input from the user
num1 = int(input('Enter the first number: '))
num2 = int(input('Enter the second number: '))

# Output the result
print("The L.C.M. is", compute_lcm(num1, num2))


Enter the first number:  4
Enter the second number:  6


The L.C.M. is 12


# Alternative way using inbulit math

In [52]:
import math

def find_lcm(a, b):
    # Calculate the GCD of the two numbers
    gcd = math.gcd(a, b)
    
    # Calculate the LCM using the formula
    lcm = abs(a * b) // gcd
    
    return lcm

# Input: two numbers
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

# Find and print the LCM
lcm = find_lcm(num1, num2)
print(f"The LCM of {num1} and {num2} is {lcm}")

Enter the first number:  5
Enter the second number:  4


The LCM of 5 and 4 is 20


In [ ]:
# Function to calculate the LCM
def find_lcm(x, y):
    # Greater number between x and y
    greater = max(x, y)

    # Keep checking multiples of the greater number until both x and y divide it
    while True:
        if greater % x == 0 and greater % y == 0:
            lcm = greater
            break
        greater += 1  # Increment the greater number
    return lcm

# Input from the user
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

# Calculate LCM
lcm = find_lcm(num1, num2)

# Output the result
print(f"The LCM of {num1} and {num2} is {lcm}.")


# 14)write a program to find the hcm 

* HCF, or Highest Common Factor, is the largest positive integer that divides two or more
numbers without leaving a remainder.


In [57]:

def compute_hcf(x, y):
    # Choose the smaller number
    if x > y:
        smaller_num = y
    else:
        smaller_num = x
    
    # Iterate from 1 to the smaller number to find the HCF
    for i in range(1, smaller_num + 1):
        if (x % i == 0) and (y % i == 0):
            hcf = i
    
    return hcf

# Input: two numbers
num1 = int(input('Enter the first number: '))
num2 = int(input('Enter the second number: '))

# Compute and print the HCF
print("The H.C.F. is", compute_hcf(num1, num2))

Enter the first number:  5
Enter the second number:  6


The H.C.F. is 1


In [60]:
import math

def compute_hcf(x, y):
    return math.gcd(x, y)

# Input: two numbers
num1 = int(input('Enter the first number: '))
num2 = int(input('Enter the second number: '))

# Compute and print the HCF
print("The H.C.F. is", compute_hcf(num1, num2))


Enter the first number:  5
Enter the second number:  6


The H.C.F. is 1


# 15) write a python program to make aa simple calculator 

In [63]:
# Define the addition function
def add(x, y):
    return x + y

# Define the subtraction function
def subtract(x, y):
    return x - y

# Define the multiplication function
def multiply(x, y):
    return x * y

# Define the divide function
def divide(x, y):
    if y != 0:
        return x / y
    else:
        return "Division by zero is not allowed!"

# Define the main calculator function
def calculator():
    print("Select operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")
    
    # Input the user's choice
    choice = input("Enter the number of your choice (1/2/3/4): ")
    
    # Input two numbers
    num1 = float(input("Enter the first number: "))
    num2 = float(input("Enter the second number: "))
    
    # Perform the selected operation
    if choice == '1':
        print(f"The result is: {add(num1, num2)}")
    elif choice == '2':
        print(f"The result is: {subtract(num1, num2)}")
    elif choice == '3':
        print(f"The result is: {multiply(num1, num2)}")
    elif choice == '4':
        print(f"The result is: {divide(num1, num2)}")
    else:
        print("Invalid input! Please select a valid operation.")

# Call the calculator function
calculator()


Select operation:
1. Add
2. Subtract
3. Multiply
4. Divide


Enter the number of your choice (1/2/3/4):  3
Enter the first number:  5
Enter the second number:  5


The result is: 25.0


# Another solution 

In [66]:
def calculator(x, y):
    a, b, c, d = x + y, x - y, x * y, x / y if y != 0 else "Division by zero is not allowed!"
    return a, b, c, d

# Input numbers
num1 = eval(input("Enter the first number: "))
num2 = eval(input("Enter the second number: "))

# Input choice
choice = int(input("Enter 1 for addition, 2 for subtraction, 3 for multiplication, 4 for division: "))

# Get results
results = calculator(num1, num2)

# Output the result based on choice
if choice in [1, 2, 3, 4]:
    print(f"The result is: {results[choice - 1]}")
else:
    print("Invalid choice!")


Enter the first number:  3
Enter the second number:  4
Enter 1 for addition, 2 for subtraction, 3 for multiplication, 4 for division:  1


The result is: 7


In [61]:
def calculator():
    operations = {'1': lambda x, y: x + y, '2': lambda x, y: x - y, 
                 '3': lambda x, y: x * y, '4': lambda x, y: x / y if y != 0 else "Error! Division by zero."}
    print("1. Addition\n2. Subtraction\n3. Multiplication\n4. Division")
    choice = input("Enter choice (1/2/3/4): ")
    if choice in operations:
        num1, num2 = float(input("Enter first number: ")), float(input("Enter second number: "))
        print(f"Result: {operations[choice](num1, num2)}")
    else:
        print("Invalid input.")

calculator()

1. Addition
2. Subtraction
3. Multiplication
4. Division


Enter choice (1/2/3/4):  1
Enter first number:  2
Enter second number:  3


Result: 5.0


# 16) write a program to calculate the BMI


* The formula to calculate BMI is: 

​* BMI = weight/height 

Weight: Measured in kilograms (kg).
Height: Measured in meters (m).


* 18.5	Underweight
* 18.5 – 24.9	Normal weight
* 25.0 – 29.9	Overweight
* 30.0 – 34.9	Obesity Class 1 (Moderate)
* 35.0 – 39.9	Obesity Class 2 (Severe)
* ≥ 40.0	Obesity Class 3 (Morbid)

In [78]:
# Input from user
weight = float(input("Enter your weight in kilograms: "))
height_cm = float(input("Enter your height in centimeters: "))

# Convert height from cm to meters
height_m = height_cm / 100

# Calculate BMI
bmi = weight / (height_m ** 2)

# Categorize BMI
if bmi < 18.5:
    category = "Underweight"
elif 18.5 <= bmi < 24.9:
    category = "Normal weight"
elif 25.0 <= bmi < 29.9:
    category = "Overweight"
elif 30.0 <= bmi < 34.9:
    category = "Obesity Class 1 (Moderate)"
elif 35.0 <= bmi < 39.9:
    category = "Obesity Class 2 (Severe)"
else:
    category = "Obesity Class 3 (Morbid)"

# Display the result
print(f"Your BMI is: {bmi:.2f}")
print(f"Category: {category}")


Enter your weight in kilograms:  70
Enter your height in centimeters:  176


Your BMI is: 22.60
Category: Normal weight


In [72]:
def calculate_bmi(weight, height):
    """Calculate BMI using the formula."""
    return weight / (height ** 2)

def categorize_bmi(bmi):
    """Categorize BMI based on standard ranges."""
    if bmi < 18.5:
        return "Underweight"
    elif 18.5 <= bmi < 24.9:
        return "Normal weight"
    elif 25.0 <= bmi < 29.9:
        return "Overweight"
    elif 30.0 <= bmi < 34.9:
        return "Obesity Class 1 (Moderate)"
    elif 35.0 <= bmi < 39.9:
        return "Obesity Class 2 (Severe)"
    else:
        return "Obesity Class 3 (Morbid)"

# Input from user
weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))

# Calculate BMI
bmi = calculate_bmi(weight, height)

# Categorize BMI
category = categorize_bmi(bmi)

# Display the result
print(f"Your BMI is: {bmi:.2f}")
print(f"Category: {category}")


Enter your weight in kilograms:  70
Enter your height in meters:  17


Your BMI is: 0.24
Category: Underweight


# 17)write a  program to find a largest element in a list 

In [84]:
list = [1, 2, 3, 4, 5]
largest_no = list[0]  
for i in list:
    if i > largest_no:
        largest_no = i
print("The largest number is:", largest_no) 

The largest number is: 5


In [89]:
list = [2,4,6,8,10]
largest =list [0]
for  i in list:
    if i>largest:
        largest = i
print(largest)

10


In [97]:
def largest_num(n):
    largest = 0
    for i in n:
        if i > largest:
            largest = i
    return largest
            
# example usage 
n = [1,2,3,4,5,6,7,9]
largest_num(n)

9

# 18)write a program to sort words in the alphabetic order


In [100]:
# Program to sort alphabetically the words from a string
my_str = input("Enter a string: ")

# Break down the string into a list of words
words = my_str.split()

# Sort the list in a case-insensitive manner
words.sort()

# Display the sorted words
print("The sorted words are:")
for word in words:
    print(word)


Enter a string:  hai bro 


The sorted words are:
bro
hai


In [101]:
# Using inbuilt method
sentence = "Sorting words alphabetically is fun and educational"
words = sentence.split()  # Split the sentence into words
words.sort()  # Sort words alphabetically using the inbuilt method
print("Sorted words (inbuilt method):", words)


Sorted words (inbuilt method): ['Sorting', 'alphabetically', 'and', 'educational', 'fun', 'is', 'words']


# 19) write a program to remove the punctuations in the string

In [112]:
import warnings
warnings.filterwarnings('ignore')


In [113]:
# Define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

# Take input from the user
my_str = input("Enter a string: ")

# Remove punctuation from the string
no_punct = ""
for char in my_str:
    if char not in punctuations:  # Proper indentation
        no_punct +=char

# Display the unpunctuated string
print("String without punctuation:", no_punct)


Enter a string:  haugdgtyteh!@#$%^&*()_+98yhai


String without punctuation: haugdgtyteh+98yhai


In [114]:
import re

def remove_punctuation_regex(text):
    # Use regex to substitute punctuation with an empty string
    return re.sub(r'[^\w\s]', '', text)   # sub search for the \w word in the a to z ,Ato Z, 0 to 9 ,-
                                          # \s that Matches any whitespace character (spaces, tabs, etc.) 
             # ^: A caret inside square brackets negates the match. So, [^...] matches anything not inside the brackets.
# Example usage
text = "Hello guys how are u!#$%^*1223^&883e2__1-'\
'\]\;"
cleaned_text = remove_punctuation_regex(text)
print("Cleaned text (using regex):", cleaned_text)

Cleaned text (using regex): Hello guys how are u1223883e2__1


In [115]:
import string

def remove_punctuation(text):
    # Create a translation table to remove punctuation
    translator = str.maketrans('', '', string.punctuation)
    # Use translate() to remove punctuation
    return text.translate(translator)

# Example usage
text = "Hello, world! This is a test: with some punctuation."
cleaned_text = remove_punctuation(text)
print("Cleaned text (using built-in methods):", cleaned_text)

Cleaned text (using built-in methods): Hello world This is a test with some punctuation


# 20) write a program to check the given number is happy number or not


* Happy Number: A Happy Number is a positive integer that, when you repeatedly replace
the number by the sum of the squares of its digits and continue the process, eventually
reaches 1. If the process never reaches 1 but instead loops endlessly in a cycle, the number
is not a Happy Number
### Explanation: Why 19 is a Happy Number

The process of checking if **19** is a Happy Number involves repeatedly summing the squares of its digits until it either reaches **1** (happy number) or enters a cycle (not a happy number). Here's the step-by-step breakdown:

1. **Step 1**: Start with the number **19**.
   * \(1^* + 9^2 = 1 + 81 = 82\)

2. **Step 2**: Take the result (**82**) and sum the squares of its digits.
*  - \*8^2 + 2^2 = 64 + 4 = 68\)

3. **Step 3**: Take the result (**68**) and sum the squares of its digits*
   * \(6^2 + 8^2 = 36 + 64 = 100\)

4. **Step 4**: Take the result (**100**) and sum the squares of its dig*ts.
*  - \*1^2 + 0^2 + 0^2 = 1 + 0 + 0 = 1\)

Since the process eventually reaches **1**, the number **19** is a **Happy Number**.

In [130]:
def is_happy_number(num):
    seen = set()  # To store previously seen numbers

    while num != 1 and num not in seen:
        seen.add(num)
        num = sum(int(i) ** 2 for i in str(num))  # Sum of squares of digits

    return num == 1

# Test the function with a number
num = int(input("Enter a number: "))
if is_happy_number(num):
    print(f"{num} is a Happy Number")
else:
    print(f"{num} is not a Happy Number")


Enter a number:  1


1 is a Happy Number


In [133]:
def is_happy_number_recursive(num, seen=None):
    if seen is None:
        seen = set()
    if num == 1:
        return True
    if num in seen:
        return False
    seen.add(num)
    num = sum(int(digit) ** 2 for digit in str(num))  # Ensure int refers to the built-in function
    return is_happy_number_recursive(num, seen)

# Test the function
number = int(input("Enter a number: "))  # Ensure int here is not overwritten
if is_happy_number_recursive(number):
    print(f"{number} is a happy number!")
else:
    print(f"{number} is not a happy number!")


Enter a number:  1


1 is a happy number!


# 21) write a program to multiple all the number in the list

In [26]:
list = [1,2,7]
a = 1
for i in list:
    a *= i
print(a)
    

14


# Alternative way

In [2]:
# Sample list of numbers
numbers = [10, 20, 30, 40, 50]
# Initialize a variable to store the sum
sum_of_numbers = 1
# Iterate through the list and accumulate the sum
for i in numbers:
 sum_of_numbers *= i
# Print the sum
print("Sum of elements in the list:", sum_of_numbers)

Sum of elements in the list: 12000000


# 22) write a program to find the duplicates in the list

In [13]:
my_list = [1, 2, 3, 1 ,0,0]
d = []
for i in my_list:
    if i not in d:  
        d.append(i) 
    else:
        print(i,end=" ") 


1 0 

In [5]:
def find_duplicates(input_list):
    duplicates = []
    for i in range(len(input_list)):
        for j in range(i + 1, len(input_list)):
            if input_list[i] == input_list[j] and input_list[i] not in duplicates:
                duplicates.append(input_list[i])
    return duplicates

# Example usage
my_list = [1, 2, 3, 2, 4, 5, 5, 6]
duplicates = find_duplicates(my_list)
print("Duplicates:", duplicates)


Duplicates: [2, 5]


In [4]:
lst = [1, 2, 3, 4, 5, 6, 1, 27]
seen = set()  
duplicates = []

for i in lst:
    if i in seen:
        duplicates.append(i) 
    else:
        seen.add(i) 

print("Duplicates:", duplicates)



Duplicates: [1]


# 23) Write a program to print sum between the starting and the ending in list


In [7]:

s = int(input("Enter the starting value")) 
e = int(input("Enter the ending value"))
b = 0
list = []
for i in range(10000):
    list.append(i)


a = list[s: e+1: 1]
print(a)
for i in a:
    b = b + i 
print(b)

Try programiz.pro


Enter the starting value 6
Enter the ending value 7


[6, 7]
13


# 24) write a program to find the smallest number in the list

In [37]:
list = [1,2,3,45]
small = 1
for i in list:
    if i < small:
        small =i


print(small)

1


# 25) Write a program to find the n number of the largest number from the list

In [39]:
def find_n_largest_elements(lst, n):
 
 sorted_lst = sorted(lst, reverse=True)

 
 largest_elements = sorted_lst[:n]

 return largest_elements
numbers = [30, 10, 45, 5, 20, 50, 15, 3, 345, 54, 67, 87, 98, 100, 34]
N = int(input("N = " ))
result = find_n_largest_elements(numbers, N)
print(f"The {N} largest elements in the list are:", result)

N =  8


The 8 largest elements in the list are: [345, 100, 98, 87, 67, 54, 50, 45]


In [44]:
def find_n_largest_elements(lst, n):
    largest_elements = []
    for _ in range(n):
        # Find the maximum element in the list
        max_element = max(lst)
        largest_elements.append(max_element)
        # Remove the maximum element from the list
        lst.remove(max_element)
    return largest_elements

numbers = [30, 10, 45, 5, 20, 50, 15, 3, 345, 54, 67, 87, 98, 100, 34]
N = int(input("N = "))
result = find_n_largest_elements(numbers, N)
print(f"The {N} largest elements in the list are:", result)


N =  6


The 6 largest elements in the list are: [345, 100, 98, 87, 67, 54]


# 26) Write a program to count the occurrences of the element in the list

In [48]:
def count_occurrences(l, element):
 count = l.count(element)
 return count
# Example usage:
my_list = [1, 2, 3, 4, 2, 5, 2, 3, 4, 6, 5]
element_to_count = 2
occurrences = count_occurrences(my_list, element_to_count)
print(f"The element {element_to_count} appears {occurrences} times in list")

The element 2 appears 3 times in list


In [49]:
def count_occurrences(l, element):
    count = 0
    for i in l:
        if i == element:
            count += 1
    return count

# Example usage:
my_list = [1, 2, 3, 4, 2, 5, 2, 3, 4, 6, 5]
element_to_count = 2
occurrences = count_occurrences(my_list, element_to_count)
print(f"The element {element_to_count} appears {occurrences} times in the list.")


The element 2 appears 3 times in the list.


# 27) Write a program split and join the string

In [56]:
str = "sri hari"
a = str.split()
for i in a:
    b = " ".join(a)
print(b)


sri hari


# 28) write a program to find the sum of two iteration is equal to given sum

In [74]:
n = [1,2,3,4,5,6,7,8]
iteration = 5
for i in range(len(n)):
    for j in range(i+1,len(n)):
        if n[i] + n[j] ==iteration:
            print(i,j)
        
        
        

0 3
1 2


In [94]:
def find_pairs_with_sum(lst, target_sum):
    pairs = []
    for i in range(len(lst)):
        for j in range(i + 1, len(lst)):
            if lst[i] + lst[j] == target_sum:
                pairs.append((lst[i], lst[j]))
    return pairs

# Example usage:
numbers = [1, 2, 3, 4, 5, 6, 7, 8]
target_sum = int(input("Enter the target sum: "))
result = find_pairs_with_sum(numbers, target_sum)
if result:
    print("Pairs with the given sum:")
    for pair in result:
        print(pair)
else:
    print("No pairs found with the given sum.")


Enter the target sum:  4


Pairs with the given sum:
(1, 3)


# 29) write a program to check the string is palindrome or not 

In [96]:
str  = "Srihari"
a = str.lower()
b=str[: :-1]
if a==b:
    print("palindrome")
else:
    print("not a palindrome")

not a palindrome


In [1]:
import re

def is_palindrome(string):

    string = re.sub(r"[^a-zA-Z0-9]", "", string)
    string = string.lower()

    return string == string[::-1]
user_input = input("Enter a string to check if it is a palindrome: ")
if is_palindrome(user_input):
    print(f'"{user_input}" is a palindrome.')
else:
    print(f'"{user_input}" is not a palindrome.')

Enter a string to check if it is a palindrome:  12321#


"12321#" is a palindrome.


# 30) Write a program to print the len of the string and list with out using the inbuilt function

In [26]:
# By using the list

list = [1,2,3,4,5]
count = 0
for i in list:
    
    count = i
print(count)

5


In [18]:
len(list)

5

In [24]:
# by using the string
str = "Srihari"
count = 0
for i in str:
    count += 1  # Increment count by 1 for each character
print(count)


7


# 31) Write a command to open the text file in the write with mode

In [111]:
file = open("filename.txt", "w")


In [112]:
# Open a file in write mode
file = open("example.txt", "w")

# Write some content to the file
file.write("This is a sample text.")

# Close the file
file.close()


# 32) write a program to sort the numerical without inbuilt 

In [1]:
lst = [30, 10, 45, 5, 20, 50, 15, 3]
sorted_list = []

while lst:
    minimum = lst[0] 
    for num in lst: 
        if num < minimum:
            minimum = num
    lst.remove(minimum)        
    sorted_list.append(minimum) 
print(sorted_list)



[3, 5, 10, 15, 20, 30, 45, 50]


# 33) remove the characters from a string except the alphabets

In [10]:
import re
string = "srihari@1-223#^"
pattern = r"[a-zA-Z]"
a = re.sub(pattern,"",string)
print(a)

@1-223#^


# 34 Write a program to find the sum of the number in the string

In [50]:
import re
sum = [ ] 
str = "sri@12334("
pattern = re.compile(r"\d+")
numbers = re.findall(pattern,str) 

print(numbers)
for i in numbers:
    sum = sum+i
print(sum)
    

['12334']


TypeError: can only concatenate list (not "str") to list

In [58]:
import re
a = 1
num_list = []

str = "sri@12334("

pattern = re.compile(r"\d+")

numbers = re.findall(pattern, str)


numbers = ",".join(numbers)
print("Extracted numbers:", numbers)
for i in numbers:
    num_list.append(int(i))
    
print("List of numbers:", num_list)

for i in num_list:
    a += i
print(a)
    

Extracted numbers: 12334
List of numbers: [1, 2, 3, 3, 4]
14


In [16]:
num = []
str = "srihari#1112@"
if str.isalpha():
    num.append(str)  
else:
    num.append("Non-alphabetic characters present")

print(num)


['Non-alphabetic characters present']


In [15]:
num = []
str = "srihari#1112@"
if str .isalpha:
    num.append(str)
print(num)

['srihari#1112@']


In [70]:
#for i in range(0,10):
a = ord("1")
print(a)

49


# 35) Reverse the string without inbuilt

In [1]:
def reverse_string(s):
    reversed_str = ""
    for char in s:
        reversed_str = char + reversed_str  # Add each character to the front of the result
    return reversed_str

# Example usage
input_str = "hello"
print(reverse_string(input_str))


olleh


In [8]:
def reverse_string(s):
    reversed_str = ""
    i = len(s) - 1  
    while i >= 0:
        reversed_str += s[i]  #We start with the last character (s[len(s) - 1]) and move backwards to the first character, 
                               #appending each character to reversed_str
        i -= 1
    return reversed_str
# Example usage
print(reverse_string("Hari"))


iraH


In [6]:

def reverse_string(s):
    return ''.join(reversed(s))
#Example Usage
reverse_string(s)

'irS'

# 36) Find the non repeating characters of a string 

In [9]:
def non_repeating_chars(s):
    seen = set()
    result = []
    
    for char in s:
        if char not in seen:
            if s.count(char) == 1:  # Check if the character appears only once
                result.append(char)
            seen.add(char)
    
    return ''.join(result)

# Example usage
input_str = "aabbccde"
print(non_repeating_chars(input_str))


de


In [11]:
def non_repeating_chars(s):
    return ''.join(filter(lambda x: s.count(x) == 1, s))

# Example usage
input_str = "aabbccde"
print(non_repeating_chars(input_str))


de


# 37) Write a basic function using the lambda function

In [14]:
x = lambda x,y:x+y
print(x(1,2))

3


In [23]:
m = lambda gender,age:(gender,age)
print(m("male",45))

('male', 45)


In [24]:
square = lambda x: x ** 2
print(square(4))


16


# 39)create a python program to print a pattern of the triangle ,Diamond 

In [34]:
def triangle_pattern(rows):
    for i in range(1, rows + 1):
        print(" " * (rows - i) + "* " * i)  # Center align the stars

rows = int(input("Enter number of rows for the triangle: "))
triangle_pattern(rows)


Enter number of rows for the triangle:  6


     * 
    * * 
   * * * 
  * * * * 
 * * * * * 
* * * * * * 


In [35]:
def print_diamond(n):
    # Upper part of diamond
    for i in range(1, n+1):
        print(" " * (n - i) + "*" * (2*i - 1))
      # this gives the odd number like the 1,3,5,7,9 because 2*1-1 =1,2*2-1 =3 
    # Lower part of diamond
    for i in range(n-1, 0, -1):
# this gives in range of the n-1 ,0,-1 step means here n is 5 .so 5-1 = 4 when it starts from the 4,0,-1 in step
        print(" " * (n - i) + "*" * (2*i - 1))

# Example usage:
rows = 5
print("\nDiamond Pattern:")
print_diamond(rows)


Diamond Pattern:
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


# 38) write a program to print number from the starting position number to the ending position number from the user by skipping the multiples of the 3

In [5]:
# Get user input for start and end numbers
start = int(input("Enter the starting number: "))
end = int(input("Enter the ending number: "))

# Loop from start to end
for num in range(start, end + 1):
    # Check if the number is a multiple of 3
    if num % 3 != 0:
        print(num)


Enter the starting number:  5
Enter the ending number:  7


5
7


In [11]:
s = 10
e = 40
list = []
for i in range(s , e+1):
    if i%3 !=0:
        list.append(i)

print(f"which are not divisible by 3 in the range of the starting and the ending:{list}")

which are not divisible by 3 in the range of the starting and the ending:[10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25, 26, 28, 29, 31, 32, 34, 35, 37, 38, 40]


# 40) write a function to claculate the area of the circle using the radius

In [ ]:
def area_of_circle(radius):
    pi = 3.14159
    return pi * radius ** 2 # pie*r**2 for cirlcle area

# Example usage
radius = 5
print(area_of_circle(radius)) 
                                    

In [12]:
# using inbulit math 
import math

def area_of_circle(radius):
    return math.pi * radius ** 2

# Example usage
radius = 5
print(area_of_circle(radius))  # Output: 78.53981633974483


78.53981633974483


In [13]:
# using the lambda function
area_of_circle = lambda radius: 3.14159 * radius ** 2

# Example usage
radius = 5
print(area_of_circle(radius))  # Output: 78.53975


78.53975


# 41) write a function to find the secound largest number in the list

In [14]:
def second_largest(nums):
    if len(nums) < 2:
        return None  # Return None if the list has fewer than 2 elements
    
    nums = list(set(nums))  # Remove duplicates using a set
    
    if len(nums) < 2:
        return None  # If there are fewer than 2 unique elements, return None
    
    nums.sort()  # Sort the list in ascending order
    return nums[-2]  # Return the second last element

# Example usage
nums = [10, 20, 4, 45, 99]
print(second_largest(nums))


45


In [15]:
def second_largest_builtin(nums):
    unique_nums = list(set(nums))  # Remove duplicates
    unique_nums.sort()             # Sort in ascending order
    return unique_nums[-2] if len(unique_nums) >= 2 else None

# Example
numbers = [5, 2, 8, 1, 9, 3]
print(second_largest_builtin(numbers))

8


# 42) create a program to generate the all prime number between the 1 and 100

In [28]:
def find_primes(n):
    primes = []  # List to store prime numbers
    
    for i in range(2, n + 1):  # Start from 2 since 1 is not a prime number
        is_prime = True
        
        for j in range(2, int(i ** 0.5) + 1):  # Check divisibility up to sqrt(i)
            if i % j == 0:
                is_prime = False
                break  # No need to check further

        if is_prime:
            primes.append(i)

    return primes

n = 100
prime_numbers = find_primes(n)
print("Prime numbers up to", n, "are:", prime_numbers)
        

Prime numbers up to 100 are: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [3]:
prime_number_list = []
for n in range(1, 101):
    if n <= 1:
        continue  # Skip non-prime numbers (0 and 1)
    
    for i in range(2, n): 
        if n % i == 0:
            break  # Not a prime number
    else:
        
        prime_number_list.append(n)
        #print("Prime number:", n)  # If no factors found, it's prime
print(prime_number_list)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


# 43)Write a program to print counts of the char in the string 

In [1]:
a="AAAbbcd"
b={}
for i in a:
    if i in b:
        b[i]+=1
    else:
        b[i]=1
        
for i,p in b.items():
    print(f"'{i}':{p}")

'A':3
'b':2
'c':1
'd':1


In [25]:
str_input = "srihari123"
s = []
c = []

for i in str_input:
    if i.isalpha():  # Check if it's a letter
        s.append(i)
    else:  # Check if it's a digit
        c.append(i)

# Creating a dictionary to map letters to their frequencies
d = {char: s.count(char) for char in set(s)}

print(f"Letters and their counts: {d}")
print(f"Digits: {c}")


Letters and their counts: {'r': 2, 's': 1, 'i': 2, 'h': 1, 'a': 1}
Digits: ['1', '2', '3']


# 44) write a program to convert the two lists into the dictionary format

In [36]:
keys = ["name", "age", "city"]
values = ["Srihari", 24, "Hyderabad"]

d = {}
for i in range(len(keys)):
    d[keys[i]] = values[i]

print(d)


{'name': 'Srihari', 'age': 24, 'city': 'Hyderabad'}


In [37]:
keys = ["name", "age", "city"]
values = ["Srihari", 24, "Hyderabad"]

d = dict(zip(keys, values))    # Having the same length of the two can from the dict
print(d)


{'name': 'Srihari', 'age': 24, 'city': 'Hyderabad'}


# 45) Write a program to extract the email id from the text by using the regex

In [4]:
import re

def extract_emails(text):
    # Regular expression pattern for matching email IDs
    email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
    
    # Find all email addresses in the text
    emails = re.findall(email_pattern, text)
    
    return emails

# Sample text
text = "Here are some email addresses: example1@example.com, test.email@domain.org, invalid-email@domain"

# Extract emails from the text
extracted_emails = extract_emails(text)

# Print the extracted emails
print("Extracted Emails:", extracted_emails)


Extracted Emails: ['example1@example.com', 'test.email@domain.org']


#                                                           oops Basic Questions

# 46) Class and Object Create a class called Student with attributes name, age, and grade. Create an object of the class and print the attributes.


In [16]:
# Defining the Student class
class Student:
    def __init__(self, name, age, grade):
        self.name = name
        self.age = age
        self.grade = grade

# Creating an object of the Student class
student1 = Student("Alice", 20, "A")

# Printing the attributes of the student object
print(f"Name: {student1.name}")
print(f"Age: {student1.age}")
print(f"Grade: {student1.grade}")


Name: Alice
Age: 20
Grade: A


# 47) create a class called Calculator with methods add, subtract, multiply, and divide. Create an object of the class and perform arithmetic operations.



In [17]:
class Calculator:
    def add(self, x, y): 
        return x + y

    def subtract(self, x, y):  
        return x - y

    def multiply(self, x, y):
        return x * y

    def divide(self, x, y):
        return x / y

calculator = Calculator()
print(calculator.add(10, 5))
print(calculator.subtract(10, 5))
print(calculator.multiply(10, 5))
print(calculator.divide(10, 5))


15
5
50
2.0


# 48) Create a class called Animal with attributes name and age. Create a subclass called Dog that inherits from Animal. Add a method bark to the Dog class. Create an object of the Dog class and print the attributes and call the bark method.

In [ ]:
# Defining the Animal class
class Animal:
    def __init__(self, name, age):
        self.name = name
        self.age = age

# Defining the Dog class that inherits from Animal
class Dog(Animal):
    def __init__(self, name, age, breed):
        # Call the constructor of the parent (Animal) class
        super().__init__(name, age)
        self.breed = breed
    
    def bark(self):
        print(f"{self.name} says: Woof!")

# Creating an object of the Dog class
dog1 = Dog("Buddy", 3, "Golden Retriever")

# Printing the attributes of the dog object
print(f"Name: {dog1.name}")
print(f"Age: {dog1.age}")
print(f"Breed: {dog1.breed}")

# Calling the bark method
dog1.bark()


# 49) Write a program to print the create the 3_D array

In [9]:
import numpy as np
Array = np.random.randint(0,100,(3,4,3))
print(Array)

[[[93  7 10]
  [46  4 63]
  [97 41 35]
  [72 48 17]]

 [[59 24 48]
  [16 63 60]
  [23 70  8]
  [ 8 75 77]]

 [[60 70 74]
  [24 37 54]
  [95 72 16]
  [37 84 50]]]


In [7]:
import numpy as np

# Generate a 3x4x3 array of random integers between 0 and 100
array = np.random.randint(0, 100, (3, 4, 3)) 
# Here the range is 0,100 and the shape of the array is like the 4,3 means that 4 rows and 3 columns
print(array)


[[[14 64 50]
  [80 90 49]
  [87 16 61]
  [84 30 53]]

 [[11 91 78]
  [21 97 24]
  [86 23 70]
  [13 59 70]]

 [[10 21 77]
  [80 83 45]
  [29 29 16]
  [45 57 46]]]


In [10]:
import numpy as np

# Generate a 3x4x5 array filled with zeros
array = np.zeros((3, 4, 5))

print(array)


[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [27]:
a = np.ones((2,4,4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
